version: '3'

services:

  app:
    build:
      dockerfile: app/Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/opt/app
      - /opt/app/node_modules # anonymous volume for node_modules only
    ports:
      - 3000:3000 # For docker to know where to redirect HMR queries

  api:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/opt/api
      - /opt/api/node_modules # anonymous volume for node_modules only
    ports:
      - 8080:8080 # unbind this in prod
      - 9229:9229 # node debugger